// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSuxvJAW4NuM4frN5SXqk12MFY4NBQLkA',
    appId: '1:1053290828352:web:6365dbbea42e96e0bc85a5',
    messagingSenderId: '1053290828352',
    projectId: 'elearning-9aeff',
    authDomain: 'elearning-9aeff.firebaseapp.com',
    storageBucket: 'elearning-9aeff.firebasestorage.app',
    measurementId: 'G-FX05HXCPBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO_pp5opYUFZYkLXPllryGB9sbiY-G0vM',
    appId: '1:1053290828352:android:c1838db91b9aa1c6bc85a5',
    messagingSenderId: '1053290828352',
    projectId: 'elearning-9aeff',
    storageBucket: 'elearning-9aeff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWn-taj5prjWy1uRKOH2lQOaGUstYGBAo',
    appId: '1:1053290828352:ios:8e679af5d00ccf97bc85a5',
    messagingSenderId: '1053290828352',
    projectId: 'elearning-9aeff',
    storageBucket: 'elearning-9aeff.firebasestorage.app',
    iosBundleId: 'com.example.eLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWn-taj5prjWy1uRKOH2lQOaGUstYGBAo',
    appId: '1:1053290828352:ios:8e679af5d00ccf97bc85a5',
    messagingSenderId: '1053290828352',
    projectId: 'elearning-9aeff',
    storageBucket: 'elearning-9aeff.firebasestorage.app',
    iosBundleId: 'com.example.eLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSuxvJAW4NuM4frN5SXqk12MFY4NBQLkA',
    appId: '1:1053290828352:web:e6db0304676a7c50bc85a5',
    messagingSenderId: '1053290828352',
    projectId: 'elearning-9aeff',
    authDomain: 'elearning-9aeff.firebaseapp.com',
    storageBucket: 'elearning-9aeff.firebasestorage.app',
    measurementId: 'G-C4HKX9WX30',
  );
}
